### ISSUE TITLE
Can't compile deepstream_redaction_app

### ISSUE THREAD

**Issue by ticlazau** [NVIDIA-AI-IOT/retinanet_for_redaction_with_deepstream#5]
Hello,

On Jetson NANO, deepstream-4.0 is install via .deb package in the:
/opt/nvidia/deepstream/deepstream-4.0
All deepstream tests are working OK on the NANO.

When I try to compile the deepstream_redaction_app I am getting bellow error:

```
make
cc -c -o src/deepstream_redaction_app.o -DPLATFORM_TEGRA -I../apps-common/includes -I../../includes -DDS_VERSION_MINOR=0 -DDS_VERSION_MAJOR=4 `pkg-config --cflags gstreamer-1.0 gstreamer-video-1.0 x11` src/deepstream_redaction_app.c
In file included from src/deepstream_redaction_app.c:28:0:
src/deepstream_app.h:34:10: fatal error: deepstream_app_version.h: No such file or directory
 #**include "deepstream_app_version.h**"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:56: recipe for target 'src/deepstream_redaction_app.o' failed
make: *** [src/deepstream_redaction_app.o] Error 1
```

Is something that I am missing?

Rgds,
Florin

**Comment by jin-nvidia** [comment]
The file in question should be at `/opt/nvidia/deepstream/deepstream-4.0/sources/apps/apps-common/includes/deepstream_app_version.h`. This comes with the manually downloaded DeepStream 4.0.2 package, or the auto-installed DeepStream 4.0.2 with the flashing of Jetpack 4.3, that appears as  `/opt/nvidia/deepstream/deepstream-4.0/`. 

Could you check that your Makefile includes the right paths, taking into consideration where your redaction app is placed?

**Comment by ticlazau** [comment]
Hello,

I have modified the Make to include the indicated folder like this:

```
CFLAGS+= -I /opt/nvidia/deepstream/deepstream-4.0/sources/includes -I /opt/nvidia/deepstream/deepstream-4.0/sources/apps/apps-common/includes -I../apps-common/incl
udes -I../../includes -DDS_VERSION_MINOR=0 -DDS_VERSION_MAJOR=4
```

However now I have another error:

```
coredump@jetson-nano:~/projects/retinanet_for_redaction_with_deepstream$ make
cc -c -o src/deepstream_redaction_app.o -DPLATFORM_TEGRA -I /opt/nvidia/deepstream/deepstream-4.0/sources/includes -I /opt/nvidia/deepstream/deepstream-4.0/sources/apps/apps-common/includes -I../apps-common/includes -I../../includes -DDS_VERSION_MINOR=0 -DDS_VERSION_MAJOR=4 `pkg-config --cflags gstreamer-1.0 gstreamer-video-1.0 x11` src/deepstream_redaction_app.c
cc -c -o src/deepstream_app_main.o -DPLATFORM_TEGRA -I /opt/nvidia/deepstream/deepstream-4.0/sources/includes -I /opt/nvidia/deepstream/deepstream-4.0/sources/apps/apps-common/includes -I../apps-common/includes -I../../includes -DDS_VERSION_MINOR=0 -DDS_VERSION_MAJOR=4 `pkg-config --cflags gstreamer-1.0 gstreamer-video-1.0 x11` src/deepstream_app_main.c
cc -c -o src/deepstream_app_config_parser.o -DPLATFORM_TEGRA -I /opt/nvidia/deepstream/deepstream-4.0/sources/includes -I /opt/nvidia/deepstream/deepstream-4.0/sources/apps/apps-common/includes -I../apps-common/includes -I../../includes -DDS_VERSION_MINOR=0 -DDS_VERSION_MAJOR=4 `pkg-config --cflags gstreamer-1.0 gstreamer-video-1.0 x11` src/deepstream_app_config_parser.c
src/deepstream_app_config_parser.c: In function ‘parse_config_file’:
src/deepstream_app_config_parser.c:218:12: **error**: too few arguments to function ‘parse_sink’
           !**parse_sink** (&config->
            ^~~~~~~~~~
In file included from src/deepstream_app_config_parser.c:24:0:
/opt/nvidia/deepstream/deepstream-4.0/sources/apps/apps-common/includes/deepstream_config_file_parser.h:131:1: note: declared here
 parse_sink (NvDsSinkSubBinConfig * config, GKeyFile * key_file, gchar * group, gchar * cfg_file_path);
 ^~~~~~~~~~
Makefile:56: recipe for target 'src/deepstream_app_config_parser.o' failed
make: *** [src/deepstream_app_config_parser.o] Error 1
```

**Comment by jin-nvidia** [comment]
I think this is a deepstream version issue. Please see the [readme](https://github.com/NVIDIA-AI-IOT/retinanet_for_redaction_with_deepstream#jetpack-compatibility) and choose the master branch if you've flashed your device with Jetpack4.2, or swithc over to the Jetpack4.3 branch.

**Comment by ticlazau** [comment]
I have flashed today the NANO with JetPack 4.3 and installed the Deepstream 4.0 from .deb file. I will try to install deepstream from tar.gz maybe will be diffrent.

**Comment by jin-nvidia** [comment]
If you flashed with JetPack4.3, then with DS4.0.2, please make sure to switch over to the correct branch after git clone. `git checkout Jetpack4.3`. The error comes from using the master branch in Jetpack4.3.

**Comment by james-nvidia** [comment]
When you install JetPack4.3, there should be a tick box for installing DeepStream at the same time. That's by far the easiest way to get DeepStream on your Jetson edge device.

**Comment by ticlazau** [comment]
Deepstream is working fine with all samples.
I believe you have an issue with the deepstream_app_config_parser.c from where the error is coming.

Here is a diff with another similar file coming with deepstreem 4.0.2

```
coredump@jetson-nano:/opt/nvidia/deepstream/deepstream-4.0/sources/apps$ diff /opt/nvidia/deepstream/deepstream-4.0/sources/apps/sample_apps/deepstream-app/deepstream_app_config_parser.c deepstream_app_config_parser.c
219,220c219
<           sink_bin_sub_bin_config[config->num_sink_sub_bins], cfg_file, *group,
<           cfg_file_path);
---
>           sink_bin_sub_bin_config[config->num_sink_sub_bins], cfg_file, *group);
```

**Comment by ticlazau** [comment]
Switching to Jetpack4.3 branch I am getting this error:

```
coredump@jetson-nano:/opt/nvidia/deepstream/deepstream-4.0/sources/apps$ make
cc -c -o src/deepstream_redaction_app.o -DPLATFORM_TEGRA -I /opt/nvidia/deepstream/deepstream-4.0/sources/apps/apps-common/includes -I /opt/nvidia/deepstream/deepstream-4.0/sources/includes -I../apps-common/includes -I../../includes -DDS_VERSION_MINOR=0 -DDS_VERSION_MAJOR=4 `pkg-config --cflags gstreamer-1.0 gstreamer-video-1.0 x11` src/deepstream_redaction_app.c
cc -c -o src/deepstream_app_main.o -DPLATFORM_TEGRA -I /opt/nvidia/deepstream/deepstream-4.0/sources/apps/apps-common/includes -I /opt/nvidia/deepstream/deepstream-4.0/sources/includes -I../apps-common/includes -I../../includes -DDS_VERSION_MINOR=0 -DDS_VERSION_MAJOR=4 `pkg-config --cflags gstreamer-1.0 gstreamer-video-1.0 x11` src/deepstream_app_main.c
cc -c -o src/deepstream_app_config_parser.o -DPLATFORM_TEGRA -I /opt/nvidia/deepstream/deepstream-4.0/sources/apps/apps-common/includes -I /opt/nvidia/deepstream/deepstream-4.0/sources/includes -I../apps-common/includes -I../../includes -DDS_VERSION_MINOR=0 -DDS_VERSION_MAJOR=4 `pkg-config --cflags gstreamer-1.0 gstreamer-video-1.0 x11` src/deepstream_app_config_parser.c
cc -o deepstream-redaction-app src/deepstream_redaction_app.o src/deepstream_app_main.o src/deepstream_app_config_parser.o -L/opt/nvidia/deepstream/deepstream-4.0/lib/ -lnvdsgst_meta -lnvds_meta -lnvdsgst_helper -lnvds_utils -lm -lgstrtspserver-1.0 -lgstrtp-1.0 -Wl,-rpath,/opt/nvidia/deepstream/deepstream-4.0/lib/ `pkg-config --libs gstreamer-1.0 gstreamer-video-1.0 x11`
src/deepstream_redaction_app.o: In function `watch_source_status':
deepstream_redaction_app.c:(.text+0x64): undefined reference to `reset_source_pipeline'
deepstream_redaction_app.c:(.text+0x68): undefined reference to `reset_source_pipeline'
src/deepstream_redaction_app.o: In function `bus_callback':
deepstream_redaction_app.c:(.text+0x428): undefined reference to `reset_source_pipeline'
deepstream_redaction_app.c:(.text+0x42c): undefined reference to `reset_source_pipeline'
src/deepstream_redaction_app.o: In function `bus_sync_handler':
deepstream_redaction_app.c:(.text+0x900): undefined reference to `set_source_to_playing'
deepstream_redaction_app.c:(.text+0x904): undefined reference to `set_source_to_playing'
src/deepstream_redaction_app.o: In function `add_and_link_broker_sink':
deepstream_redaction_app.c:(.text+0x17dc): undefined reference to `link_element_to_tee_src_pad'
src/deepstream_redaction_app.o: In function `create_processing_instance':
deepstream_redaction_app.c:(.text+0x1908): undefined reference to `create_sink_bin'
deepstream_redaction_app.c:(.text+0x1984): undefined reference to `create_osd_bin'
src/deepstream_redaction_app.o: In function `create_common_elements':
deepstream_redaction_app.c:(.text+0x1d5c): undefined reference to `create_secondary_gie_bin'
deepstream_redaction_app.c:(.text+0x1efc): undefined reference to `create_tracking_bin'
deepstream_redaction_app.c:(.text+0x20ac): undefined reference to `create_primary_gie_bin'
src/deepstream_redaction_app.o: In function `create_pipeline':
deepstream_redaction_app.c:(.text+0x28ec): undefined reference to `create_multi_source_bin'
deepstream_redaction_app.c:(.text+0x295c): undefined reference to `set_streammux_properties'
deepstream_redaction_app.c:(.text+0x2b2c): undefined reference to `create_tiled_display_bin'
deepstream_redaction_app.c:(.text+0x2f48): undefined reference to `create_dsexample_bin'
deepstream_redaction_app.c:(.text+0x325c): undefined reference to `enable_perf_measurement'
src/deepstream_redaction_app.o: In function `pause_pipeline':
deepstream_redaction_app.c:(.text+0x3998): undefined reference to `pause_perf_measurement'
src/deepstream_redaction_app.o: In function `resume_pipeline':
deepstream_redaction_app.c:(.text+0x3a84): undefined reference to `resume_perf_measurement'
src/deepstream_app_main.o: In function `all_bbox_generated':
deepstream_app_main.c:(.text+0x160): undefined reference to `str_replace'
deepstream_app_main.c:(.text+0x188): undefined reference to `str_replace'
deepstream_app_main.c:(.text+0x1e4): undefined reference to `str_replace'
deepstream_app_main.c:(.text+0x20c): undefined reference to `str_replace'
src/deepstream_app_config_parser.o: In function `parse_tests':
deepstream_app_config_parser.c:(.text+0x78): undefined reference to `APP_CFG_PARSER_CAT'
deepstream_app_config_parser.c:(.text+0x7c): undefined reference to `APP_CFG_PARSER_CAT'
deepstream_app_config_parser.c:(.text+0x150): undefined reference to `APP_CFG_PARSER_CAT'
deepstream_app_config_parser.c:(.text+0x154): undefined reference to `APP_CFG_PARSER_CAT'
src/deepstream_app_config_parser.o: In function `parse_app':
deepstream_app_config_parser.c:(.text+0x308): undefined reference to `APP_CFG_PARSER_CAT'
src/deepstream_app_config_parser.o:deepstream_app_config_parser.c:(.text+0x30c): more undefined references to `APP_CFG_PARSER_CAT' follow
src/deepstream_app_config_parser.o: In function `parse_app':
deepstream_app_config_parser.c:(.text+0x554): undefined reference to `get_absolute_file_path'
deepstream_app_config_parser.c:(.text+0x584): undefined reference to `APP_CFG_PARSER_CAT'
deepstream_app_config_parser.c:(.text+0x588): undefined reference to `APP_CFG_PARSER_CAT'
deepstream_app_config_parser.c:(.text+0x62c): undefined reference to `get_absolute_file_path'
deepstream_app_config_parser.c:(.text+0x65c): undefined reference to `APP_CFG_PARSER_CAT'
deepstream_app_config_parser.c:(.text+0x660): undefined reference to `APP_CFG_PARSER_CAT'
src/deepstream_app_config_parser.o: In function `parse_config_file':
deepstream_app_config_parser.c:(.text+0x7ec): undefined reference to `APP_CFG_PARSER_CAT'
deepstream_app_config_parser.c:(.text+0x7f0): undefined reference to `APP_CFG_PARSER_CAT'
deepstream_app_config_parser.c:(.text+0x800): undefined reference to `APP_CFG_PARSER_CAT'
src/deepstream_app_config_parser.o:deepstream_app_config_parser.c:(.text+0x804): more undefined references to `APP_CFG_PARSER_CAT' follow
src/deepstream_app_config_parser.o: In function `parse_config_file':
deepstream_app_config_parser.c:(.text+0xa28): undefined reference to `parse_source'
deepstream_app_config_parser.c:(.text+0xab8): undefined reference to `parse_streammux'
deepstream_app_config_parser.c:(.text+0xb04): undefined reference to `parse_osd'
deepstream_app_config_parser.c:(.text+0xb64): undefined reference to `parse_gie'
deepstream_app_config_parser.c:(.text+0xbb4): undefined reference to `parse_tracker'
deepstream_app_config_parser.c:(.text+0xc6c): undefined reference to `parse_gie'
deepstream_app_config_parser.c:(.text+0xd74): undefined reference to `parse_sink'
deepstream_app_config_parser.c:(.text+0xe10): undefined reference to `parse_tiled_display'
deepstream_app_config_parser.c:(.text+0xe5c): undefined reference to `parse_dsexample'
deepstream_app_config_parser.c:(.text+0xed0): undefined reference to `APP_CFG_PARSER_CAT'
deepstream_app_config_parser.c:(.text+0xed4): undefined reference to `APP_CFG_PARSER_CAT'
collect2: error: ld returned 1 exit status
Makefile:59: recipe for target 'deepstream-redaction-app' failed
make: *** [deepstream-redaction-app] Error 1
```

**Comment by jin-nvidia** [comment]
Just to make sure, are you running `make` in the folder `/opt/nvidia/deepstream/deepstream-4.0/sources/apps/retinanet_for_redaction_with_deepstream`?  

On Xavier, running the following command returns no difference:
`nvidia@nvidia-desktop:/opt/nvidia/deepstream/deepstream-4.0/sources/apps/retinanet_for_redaction_with_deepstream$ diff src/deepstream_app_config_parser.c ../sample_apps/deepstream-app/deepstream_app_config_parser.c `

All I've done before `make` is `git clone` and `git checkout`.

We've only tested on Xavier so far, when time allows we will also test on Nano.

**Comment by ticlazau** [comment]
@jin-nvidia is OK now, THX

1. work with the jetpack4.3 branch
2. copy the retinanet_for_redaction_with_deepstream directory and not only the Make and /src folder in the /opt/nvidia/deepstream/deepstream-4.0/sources/apps

All good now, thank you!
